### ISSUE TITLE
where can i find the data？

### ISSUE THREAD

**Issue by SRenye** [donaldmunro/TangoCamera#1]
hello！I have downloaded this app，and it is wonderful! But where can I find the image and the file(.ply)?
Do I need a SD card?(I have just bought aa Lenovo phab 2 PRO)

**Comment by donaldmunro** [comment]
It should be saved to the DCIM directory in subdirectory TangoCamera, which on most devices will be /sdcard/DCIM/TangoCamera. You can fetch the directory using adb:
adb pull /sdcard/DCIM/TangoCamera

**Comment by donaldmunro** [comment]
I have added the directory location to the README.
